spring:
  data:
    mongodb:
      username: fayupable
      password: fayupable
      host: localhost
      port: 27017
      database: restaurant
      authentication-database: admin
server:
  port: 8090
